# 基础开发镜像；根据情况进行修改
FROM lightrag:v251216                     

WORKDIR /workspace/lightrag               # 根据情况进行修改

# 安装系统工具
RUN apt-get update && \
    apt-get install -y vim curl net-tools && \
    rm -rf /var/lib/apt/lists/*

# 安装 pip / uv 并配置国内源
# RUN python -m pip install --upgrade pip && \
#     pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
# RUN pip install uv && \
#     uv config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# 默认启动 bash
CMD ["bash"]